# Generated by Django 4.1.7 on 2023-02-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=100)),
                ('experiance', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
